// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace mac{
	public class Value
	{
		public Value ()
		{

		}

		public static int run() {
			byte b = 1;
			Console.WriteLine(b);
			char c = 'f';
			Console.WriteLine(c);
			bool bo = true;
			Console.WriteLine(bo);
			SByte sb = -11;
			Console.WriteLine(sb);
			sbyte sb2 = -11;
			Console.WriteLine(sb2);
			Console.WriteLine(sb == sb2);
			Single si = 11.11f;
			Console.WriteLine(si);
			return 0;
		}
	}
}

